spring:
  application:
    name: crack-sensing-ai-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

aws:
  region: ${AWS_REGION:ap-northeast-2}

s3:
  bucket-name: ${S3_BUCKET_NAME}

server:
  port: 8080
